// let Abhi=document.getElementsByTagName('h1');
// for(let key in Abhi)
// {
//   console.log(Abhi[key]);
// }
// let class1 = document.getElementsByClassName('.class1');
// console.log(class1);
// let id1 = document.getElementById('id1');
// console.log(id1);
// let kabhi = document.querySelector('#id1')
// console.log(kabhi);
// let kabhi2 = document.querySelectorAll('#class1');
// console.log(kabhi2);
// let kabhi = document.querySelector("ul");
// console.log(kabhi.innerHTML);

// let kabhi2 = document.querySelector("p");
// kabhi2.innerHTML = 'Abhishek Shukla is a good boy';
// console.log(kabhi2.innerHTML);


let kabhi = document.getElementsByTagName("h1");
kabhi[3].style.backgroundColor = 'red';
kabhi[3].style.Color = 'gray';


// let myli = document.getElementsByTagName('li');
// console.log(myli);